'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 14.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace AdminAndAuthTest
    
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''adminLogin - Use 'adminLoginParams' to pass parameters into this method.
        '''</summary>
        Public Sub adminLogin()
            Dim uIChromeLegacyWindowDocument As WinControl = Me.UILogowanieSystemzarząWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(887, 278))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(259, 133))

            'Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, New Point(267, 133))
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -95, -6)

            'Type '{Back}{Back}{Back}{Back}{Back}admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminLoginParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(233, 316))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(238, 166))

            'Type 'admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminLoginParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(238, 234))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(151, 188))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(152, 208))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(749, 38))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(658, 37))
        End Sub
        
        '''<summary>
        '''adminAddUser - Use 'adminAddUserParams' to pass parameters into this method.
        '''</summary>
        Public Sub adminAddUser()
            Dim uIChromeLegacyWindowDocument As WinControl = Me.UILogowanieSystemzarząWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(643, 19))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(319, 136))

            'Type 'newUser' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(360, 150))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(363, 165))

            'Type 's{Delete}{Back}new@user.pl' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(322, 210))

            'Type 'hh1234' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(381, 235))

            'Type 'hh1234' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys3, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(348, 292))

            'Type 'username' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys4, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(314, 308))

            'Type 'userlname' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, Me.adminAddUserParams.UIChromeLegacyWindowDocumentSendKeys5, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(239, 353))
        End Sub
        
        '''<summary>
        '''adminAddUserExist - Use 'adminAddUserExistParams' to pass parameters into this method.
        '''</summary>
        Public Sub adminAddUserExist()
            Dim uIChromeLegacyWindowDocument As WinControl = Me.UILogowanieSystemzarząWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument
            Dim uIDodajużytkownikaSystDocument As WinControl = Me.UILogowanieSystemzarząWindow.UIChromeLegacyWindowWindow.UIDodajużytkownikaSystDocument

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(640, 21))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(279, 138))

            'Type 'newUser' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(324, 191))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(312, 175))

            'Type 'new' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys1, ModifierKeys.None)

            'Type '{LShiftKey}@user.pl' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys2, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(579, 177))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(435, 208))

            'Type 'kakakak' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys3, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(400, 237))

            'Type 'kakakak' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys4, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(359, 287))

            'Type '{LShiftKey}im' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys5, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(492, 318))

            'Type 'naz' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
            Keyboard.SendKeys(uIDodajużytkownikaSystDocument, Me.adminAddUserExistParams.UIDodajużytkownikaSystDocumentSendKeys6, ModifierKeys.None)

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(325, 398))

            'Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(253, 356))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property adminLoginParams() As adminLoginParams
            Get
                If (Me.madminLoginParams Is Nothing) Then
                    Me.madminLoginParams = New adminLoginParams()
                End If
                Return Me.madminLoginParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property adminAddUserParams() As adminAddUserParams
            Get
                If (Me.madminAddUserParams Is Nothing) Then
                    Me.madminAddUserParams = New adminAddUserParams()
                End If
                Return Me.madminAddUserParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property adminAddUserExistParams() As adminAddUserExistParams
            Get
                If (Me.madminAddUserExistParams Is Nothing) Then
                    Me.madminAddUserExistParams = New adminAddUserExistParams()
                End If
                Return Me.madminAddUserExistParams
            End Get
        End Property
        
        Public ReadOnly Property UILogowanieSystemzarząWindow() As UILogowanieSystemzarząWindow
            Get
                If (Me.mUILogowanieSystemzarząWindow Is Nothing) Then
                    Me.mUILogowanieSystemzarząWindow = New UILogowanieSystemzarząWindow()
                End If
                Return Me.mUILogowanieSystemzarząWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private madminLoginParams As adminLoginParams
        
        Private madminAddUserParams As adminAddUserParams
        
        Private madminAddUserExistParams As adminAddUserExistParams
        
        Private mUILogowanieSystemzarząWindow As UILogowanieSystemzarząWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'adminLogin'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Public Class adminLoginParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Back}{Back}{Back}{Back}{Back}admin' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys As String = "{Back}{Back}{Back}{Back}{Back}admin"
        
        '''<summary>
        '''Type 'admin' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys1 As String = "admin"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'adminAddUser'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Public Class adminAddUserParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'newUser' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys As String = "newUser"
        
        '''<summary>
        '''Type 's{Delete}{Back}new@user.pl' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys1 As String = "s{Delete}{Back}new@user.pl"
        
        '''<summary>
        '''Type 'hh1234' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys2 As String = "hh1234"
        
        '''<summary>
        '''Type 'hh1234' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys3 As String = "hh1234"
        
        '''<summary>
        '''Type 'username' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys4 As String = "username"
        
        '''<summary>
        '''Type 'userlname' in 'Chrome Legacy Window' document
        '''</summary>
        Public UIChromeLegacyWindowDocumentSendKeys5 As String = "userlname"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'adminAddUserExist'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Public Class adminAddUserExistParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'newUser' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys As String = "newUser"
        
        '''<summary>
        '''Type 'new' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys1 As String = "new"
        
        '''<summary>
        '''Type '{LShiftKey}@user.pl' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys2 As String = "{LShiftKey}@user.pl"
        
        '''<summary>
        '''Type 'kakakak' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys3 As String = "kakakak"
        
        '''<summary>
        '''Type 'kakakak' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys4 As String = "kakakak"
        
        '''<summary>
        '''Type '{LShiftKey}im' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys5 As String = "{LShiftKey}im"
        
        '''<summary>
        '''Type 'naz' in 'Dodaj użytkownika - System zarządzania fakturami -...' document
        '''</summary>
        Public UIDodajużytkownikaSystDocumentSendKeys6 As String = "naz"
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Public Class UILogowanieSystemzarząWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Logowanie - System zarządzania fakturami - Google Chrome"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Chrome_WidgetWin_1"
            Me.WindowTitles.Add("Logowanie - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Zarządzanie użytkownikami - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Dodaj użytkownika - System zarządzania fakturami - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowWindow() As UIChromeLegacyWindowWindow
            Get
                If (Me.mUIChromeLegacyWindowWindow Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow = New UIChromeLegacyWindowWindow(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowWindow As UIChromeLegacyWindowWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "14.0.23107.0")>  _
    Public Class UIChromeLegacyWindowWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "318360000"
            Me.WindowTitles.Add("Logowanie - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Zarządzanie użytkownikami - System zarządzania fakturami - Google Chrome")
            Me.WindowTitles.Add("Dodaj użytkownika - System zarządzania fakturami - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowDocument() As WinControl
            Get
                If (Me.mUIChromeLegacyWindowDocument Is Nothing) Then
                    Me.mUIChromeLegacyWindowDocument = New WinControl(Me)
                    Me.mUIChromeLegacyWindowDocument.SearchProperties(UITestControl.PropertyNames.ControlType) = "Document"
                    Me.mUIChromeLegacyWindowDocument.WindowTitles.Add("Logowanie - System zarządzania fakturami - Google Chrome")
                    Me.mUIChromeLegacyWindowDocument.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami - Google Chrome")
                    Me.mUIChromeLegacyWindowDocument.WindowTitles.Add("Zarządzanie użytkownikami - System zarządzania fakturami - Google Chrome")
                End If
                Return Me.mUIChromeLegacyWindowDocument
            End Get
        End Property
        
        Public ReadOnly Property UIDodajużytkownikaSystDocument() As WinControl
            Get
                If (Me.mUIDodajużytkownikaSystDocument Is Nothing) Then
                    Me.mUIDodajużytkownikaSystDocument = New WinControl(Me)
                    Me.mUIDodajużytkownikaSystDocument.SearchProperties(UITestControl.PropertyNames.ControlType) = "Document"
                    Me.mUIDodajużytkownikaSystDocument.WindowTitles.Add("Dodaj użytkownika - System zarządzania fakturami - Google Chrome")
                End If
                Return Me.mUIDodajużytkownikaSystDocument
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowDocument As WinControl
        
        Private mUIDodajużytkownikaSystDocument As WinControl
        #End Region
    End Class
End Namespace
