// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UserFunctionalTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;


    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {

        /// <summary>
        /// fillAddPartnerParameters - Use 'fillAddPartnerParametersParams' to pass parameters into this method.
        /// </summary>
        public string fillAddPartnerParameters()
        {
            #region Variable Declarations
            HtmlEdit uILoginEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILoginEdit;
            HtmlEdit uIPasswordEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UIPasswordEdit;
            HtmlButton uILogInButton = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILogInFormCustom.UILogInButton;
            HtmlHyperlink uIDodajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UIDodajpartneraHyperlink;
            HtmlEdit uIFirstNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UILastNameEdit;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UICompanyNameEdit;
            HtmlEdit uIVATINEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIVATINEdit;
            HtmlEdit uIAddressEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIAddressEdit;
            #endregion

            // Type 'admin@admin.com' in 'email' text box
            uILoginEdit.Text = this.fillAddPartnerParametersParams.UIEmailEditText;

            // Type '{Tab}' in 'email' text box
            Keyboard.SendKeys(uILoginEdit, this.fillAddPartnerParametersParams.UIEmailEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.fillAddPartnerParametersParams.UIPasswordEditPassword;

            // Click 'Log In' button
            Mouse.Click(uILogInButton, new Point(21, 16));

            // Click 'Dodaj partnera' link
            Mouse.Click(uIDodajpartneraHyperlink, new Point(79, 24));

            // Type 'TestFirstName' in 'firstName' text box
            uIFirstNameEdit.Text = this.fillAddPartnerParametersParams.UIFirstNameEditText;

            // Type '{Tab}' in 'firstName' text box
            Keyboard.SendKeys(uIFirstNameEdit, this.fillAddPartnerParametersParams.UIFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'TestLastName' in 'lastName' text box
            uILastNameEdit.Text = this.fillAddPartnerParametersParams.UILastNameEditText;

            // Type '{Tab}' in 'lastName' text box
            Keyboard.SendKeys(uILastNameEdit, this.fillAddPartnerParametersParams.UILastNameEditSendKeys, ModifierKeys.None);

            // Type 'TestCompanyName' in 'companyName' text box
            uICompanyNameEdit.Text = this.fillAddPartnerParametersParams.UICompanyNameEditText;

            // Type '{Tab}' in 'companyName' text box
            Keyboard.SendKeys(uICompanyNameEdit, this.fillAddPartnerParametersParams.UICompanyNameEditSendKeys, ModifierKeys.None);

            // Type '1234567890' in 'VATIN' text box
            string vatin = "1234567890" + new Random().Next(9999999).ToString();
            uIVATINEdit.Text = vatin;

            // Type '{Tab}' in 'VATIN' text box
            Keyboard.SendKeys(uIVATINEdit, this.fillAddPartnerParametersParams.UIVATINEditSendKeys, ModifierKeys.None);

            // Type 'TestAddress' in 'address' text box
            uIAddressEdit.Text = this.fillAddPartnerParametersParams.UIAddressEditText;

            return vatin;
        }

        public string addPartnersToSearch()
        {
            #region Variable Declarations
            HtmlEdit uILoginEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILoginEdit;
            HtmlEdit uIPasswordEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UIPasswordEdit;
            HtmlButton uILogInButton = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILogInFormCustom.UILogInButton;
            HtmlHyperlink uIDodajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UIDodajpartneraHyperlink;
            HtmlEdit uIFirstNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UILastNameEdit;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UICompanyNameEdit;
            HtmlEdit uIVATINEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIVATINEdit;
            HtmlEdit uIAddressEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIAddressEdit;
            #endregion

            uILoginEdit.Text = this.fillAddPartnerParametersParams.UIEmailEditText;
            Keyboard.SendKeys(uILoginEdit, this.fillAddPartnerParametersParams.UIEmailEditSendKeys, ModifierKeys.None);
            uIPasswordEdit.Password = this.fillAddPartnerParametersParams.UIPasswordEditPassword;
            Mouse.Click(uILogInButton, new Point(21, 16));
            Mouse.Click(uIDodajpartneraHyperlink, new Point(79, 24));
            uIFirstNameEdit.Text = "Name_1";
            Keyboard.SendKeys(uIFirstNameEdit, this.fillAddPartnerParametersParams.UIFirstNameEditSendKeys, ModifierKeys.None);
            uILastNameEdit.Text = "LastName_1";
            Keyboard.SendKeys(uILastNameEdit, this.fillAddPartnerParametersParams.UILastNameEditSendKeys, ModifierKeys.None);
            uICompanyNameEdit.Text = "Company_ToSearch";
            Keyboard.SendKeys(uICompanyNameEdit, this.fillAddPartnerParametersParams.UICompanyNameEditSendKeys, ModifierKeys.None);
            string vatin = "1234567890" + new Random().Next(9999999).ToString();
            uIVATINEdit.Text = vatin;
            Keyboard.SendKeys(uIVATINEdit, this.fillAddPartnerParametersParams.UIVATINEditSendKeys, ModifierKeys.None);
            uIAddressEdit.Text = "Address_1";

            return vatin;
        }

        public string addSecondPartnerToSearch()
        {
            #region Variable Declarations
            HtmlHyperlink uIDodajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UIDodajpartneraHyperlink;
            HtmlEdit uIFirstNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UILastNameEdit;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UICompanyNameEdit;
            HtmlEdit uIVATINEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIVATINEdit;
            HtmlEdit uIAddressEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIAddressEdit;
            #endregion

            // Click 'Dodaj partnera' link
            Mouse.Click(uIDodajpartneraHyperlink, new Point(89, 26));

            // Type 'testName' in 'firstName' text box
            uIFirstNameEdit.Text = "Name_2";
            Keyboard.SendKeys(uIFirstNameEdit, this.fillTheSecondPartnerParams.UIFirstNameEditSendKeys, ModifierKeys.None);
            uILastNameEdit.Text = "LastName_2";
            Keyboard.SendKeys(uILastNameEdit, this.fillTheSecondPartnerParams.UILastNameEditSendKeys, ModifierKeys.None);
            uICompanyNameEdit.Text = "Company_ToSearch";
            Keyboard.SendKeys(uICompanyNameEdit, this.fillTheSecondPartnerParams.UICompanyNameEditSendKeys, ModifierKeys.None);
            string vatin = "1234567890" + new Random().Next(9999999).ToString();
            uIVATINEdit.Text = vatin;
            Keyboard.SendKeys(uIVATINEdit, this.fillTheSecondPartnerParams.UIVATINEditSendKeys, ModifierKeys.None);
            uIAddressEdit.Text = "Address_2";

            return vatin;
        }

        public void findPartnersInTheSameCompanyAction()
        {
            #region Variable Declarations
            HtmlHyperlink uISzukajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UISzukajpartneraHyperlink;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UISearchInvoiceSystemzDocument.UICompanyNameEdit;
            HtmlButton uISzukajButton = this.UILogowanieSystemzarząWindow.UISearchInvoiceSystemzDocument.UISzukajButton;
            #endregion

            // Click 'Szukaj partnera' link
            Mouse.Click(uISzukajpartneraHyperlink, new Point(42, 28));

            // Type 'Company_ToSearch' in 'companyName' text box
            uICompanyNameEdit.Text = "Company_ToSearch";

            // Click 'Szukaj' button
            Mouse.Click(uISzukajButton, new Point(42, 10));
        }

        public void companyAssertion(string v1, string v2)
        {
            #region Variable Declarations
            HtmlDocument uISearchInvoiceSystemzDocument = this.UILogowanieSystemzarząWindow.UISearchInvoiceSystemzDocument;
            #endregion

            StringAssert.Contains(uISearchInvoiceSystemzDocument.InnerText, v1);
            StringAssert.Contains(uISearchInvoiceSystemzDocument.InnerText, v2);
        }

        /// <summary>
        /// addPartnerParameterAssertions
        /// </summary>
        public void addPartnerParameterAssertions()
        {
            #region Variable Declarations
            HtmlEdit uIFirstNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UILastNameEdit;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UICompanyNameEdit;
            HtmlEdit uIVATINEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIVATINEdit;
            HtmlEdit uIAddressEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIAddressEdit;
            #endregion

            // Verify that the 'Text' property of 'firstName' text box is not equal to 'null'
            Assert.IsNotNull(uIFirstNameEdit.Text);

            // Verify that the 'Text' property of 'lastName' text box is not equal to 'null'
            Assert.IsNotNull(uILastNameEdit.Text);

            // Verify that the 'Text' property of 'companyName' text box is not equal to 'null'
            Assert.IsNotNull(uICompanyNameEdit.Text);

            // Verify that the 'Text' property of 'VATIN' text box is not equal to 'null'
            Assert.IsNotNull(uIVATINEdit.Text);

            // Verify that the 'Text' property of 'address' text box is not equal to 'null'
            Assert.IsNotNull(uIAddressEdit.Text);
        }

        /// <summary>
        /// addPartnerSubmitAction
        /// </summary>
        public void addPartnerSubmitAction()
        {
            #region Variable Declarations
            HtmlButton uIDodajButton = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIDodajButton;
            #endregion

            // Click 'Dodaj' button
            Mouse.Click(uIDodajButton, new Point(46, 12));
        }

        /// <summary>
        /// listPartnersAction
        /// </summary>
        public void listPartnersAction()
        {
            #region Variable Declarations
            HtmlHyperlink uISzukajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UISzukajpartneraHyperlink;
            HtmlButton uISzukajButton = this.UILogowanieSystemzarząWindow.UISearchInvoiceSystemzDocument.UISzukajButton;
            #endregion

            // Click 'Szukaj partnera' link
            Mouse.Click(uISzukajpartneraHyperlink, new Point(54, 26));

            // Click 'Szukaj' button
            Mouse.Click(uISzukajButton, new Point(46, 13));
        }

        /// <summary>
        /// vatinAssertion - Use 'vatinAssertionExpectedValues' to pass parameters into this method.
        /// </summary>
        public void vatinAssertion(string vatin)
        {
            #region Variable Declarations
            HtmlDocument uISearchInvoiceSystemzDocument = this.UILogowanieSystemzarząWindow.UISearchInvoiceSystemzDocument;
            #endregion

            StringAssert.Contains(uISearchInvoiceSystemzDocument.InnerText, vatin);
        }

        /// <summary>
        /// fillTheSecondPartner - Use 'fillTheSecondPartnerParams' to pass parameters into this method.
        /// </summary>
        public void fillTheSecondPartner(string vatin)
        {
            #region Variable Declarations
            HtmlHyperlink uIDodajpartneraHyperlink = this.UILogowanieSystemzarząWindow.UIWyszukiwarkafakturSyDocument.UIDodajpartneraHyperlink;
            HtmlEdit uIFirstNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UILastNameEdit;
            HtmlEdit uICompanyNameEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UICompanyNameEdit;
            HtmlEdit uIVATINEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIVATINEdit;
            HtmlEdit uIAddressEdit = this.UILogowanieSystemzarząWindow.UIAddPartnerSystemzarzDocument.UIAddressEdit;
            #endregion

            // Click 'Dodaj partnera' link
            Mouse.Click(uIDodajpartneraHyperlink, new Point(89, 26));

            // Type 'testName' in 'firstName' text box
            uIFirstNameEdit.Text = this.fillTheSecondPartnerParams.UIFirstNameEditText;

            // Type '{Tab}' in 'firstName' text box
            Keyboard.SendKeys(uIFirstNameEdit, this.fillTheSecondPartnerParams.UIFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'testLastName' in 'lastName' text box
            uILastNameEdit.Text = this.fillTheSecondPartnerParams.UILastNameEditText;

            // Type '{Tab}' in 'lastName' text box
            Keyboard.SendKeys(uILastNameEdit, this.fillTheSecondPartnerParams.UILastNameEditSendKeys, ModifierKeys.None);

            // Type 'testCompanyName' in 'companyName' text box
            uICompanyNameEdit.Text = this.fillTheSecondPartnerParams.UICompanyNameEditText;

            // Type '{Tab}' in 'companyName' text box
            Keyboard.SendKeys(uICompanyNameEdit, this.fillTheSecondPartnerParams.UICompanyNameEditSendKeys, ModifierKeys.None);

            // Type '1' in 'VATIN' text box
            uIVATINEdit.Text = vatin;

            // Type '{Tab}' in 'VATIN' text box
            Keyboard.SendKeys(uIVATINEdit, this.fillTheSecondPartnerParams.UIVATINEditSendKeys, ModifierKeys.None);

            // Type 'address' in 'address' text box
            uIAddressEdit.Text = this.fillTheSecondPartnerParams.UIAddressEditText;
        }

        #region Properties
        public virtual fillAddPartnerParametersParams fillAddPartnerParametersParams
        {
            get
            {
                if ((this.mfillAddPartnerParametersParams == null))
                {
                    this.mfillAddPartnerParametersParams = new fillAddPartnerParametersParams();
                }
                return this.mfillAddPartnerParametersParams;
            }
        }

        public virtual vatinAssertionExpectedValues vatinAssertionExpectedValues
        {
            get
            {
                if ((this.mvatinAssertionExpectedValues == null))
                {
                    this.mvatinAssertionExpectedValues = new vatinAssertionExpectedValues();
                }
                return this.mvatinAssertionExpectedValues;
            }
        }

        public virtual fillTheSecondPartnerParams fillTheSecondPartnerParams
        {
            get
            {
                if ((this.mfillTheSecondPartnerParams == null))
                {
                    this.mfillTheSecondPartnerParams = new fillTheSecondPartnerParams();
                }
                return this.mfillTheSecondPartnerParams;
            }
        }

        public UILogowanieSystemzarząWindow UILogowanieSystemzarząWindow
        {
            get
            {
                if ((this.mUILogowanieSystemzarząWindow == null))
                {
                    this.mUILogowanieSystemzarząWindow = new UILogowanieSystemzarząWindow();
                }
                return this.mUILogowanieSystemzarząWindow;
            }
        }
        #endregion

        #region Fields
        private fillAddPartnerParametersParams mfillAddPartnerParametersParams;

        private vatinAssertionExpectedValues mvatinAssertionExpectedValues;

        private fillTheSecondPartnerParams mfillTheSecondPartnerParams;

        private UILogowanieSystemzarząWindow mUILogowanieSystemzarząWindow;
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'fillAddPartnerParameters'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class fillAddPartnerParametersParams
    {

        #region Fields
        /// <summary>
        /// Type 'admin@admin.com' in 'email' text box
        /// </summary>
        public string UIEmailEditText = "admin@admin.com";

        /// <summary>
        /// Type '{Tab}' in 'email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "{Tab}";

        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "QWwOodIXpSM441BCNCWNvH9k+8fhegdI";

        /// <summary>
        /// Type 'TestFirstName' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditText = "TestFirstName";

        /// <summary>
        /// Type '{Tab}' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'TestLastName' in 'lastName' text box
        /// </summary>
        public string UILastNameEditText = "TestLastName";

        /// <summary>
        /// Type '{Tab}' in 'lastName' text box
        /// </summary>
        public string UILastNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'TestCompanyName' in 'companyName' text box
        /// </summary>
        public string UICompanyNameEditText = "TestCompanyName";

        /// <summary>
        /// Type '{Tab}' in 'companyName' text box
        /// </summary>
        public string UICompanyNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type '1234567890' in 'VATIN' text box
        /// </summary>
        public string UIVATINEditText = "1234567890";

        /// <summary>
        /// Type '{Tab}' in 'VATIN' text box
        /// </summary>
        public string UIVATINEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'TestAddress' in 'address' text box
        /// </summary>
        public string UIAddressEditText = "TestAddress";
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'vatinAssertion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class vatinAssertionExpectedValues
    {

        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'SearchInvoice - System zarządzania fakturami' document contains 'ASDASDASD
        ///
        ///
        ///
        ///
        /// Faktury 
        ///
        ///Dodaj fakturę
        ///
        ///
        ///Dodaj partnera
        ///
        ///
        ///Szukaj partnera
        ///
        ///
        ///Rejestracja
        ///
        ///
        ///Dodaj użytkownika
        ///
        ///
        ///Zarządzanie użytkownikami
        ///
        ///
        ///Wyloguj się
        ///
        ///
        ///
        ///
        ///Szukaj partnerów
        ///
        ///
        ///
        ///Imię  
        ///Nazwisko  
        ///Firma  
        ///VATIN  
        ///
        ///
        ///Szukaj 
        ///
        ///
        ///
        ///Imię
        ///
        ///Nazwisko
        ///
        ///Firma
        ///
        ///VATIN
        ///
        ///Adres
        ///
        ///
        ///TestFirstName
        ///
        ///TestLastName
        ///
        ///TestCompanyName
        ///
        ///1234567890
        ///
        ///TestAddress
        ///
        ///
        ///TestFirstName
        ///
        ///TestLastName
        ///
        ///TestCompanyName
        ///
        ///123456789054907346
        ///
        ///TestAddress
        ///
        ///
        ///
        ///
        ///© 2016 - System zarządzania fakturami
        ///        {"appName":"Internet Explorer","requestId":"f5b2d638161b48cc86da171dd64b9451"}    '
        /// </summary>
        public string UISearchInvoiceSystemzDocumentInnerText = @"ASDASDASD




 Faktury 

Dodaj fakturę


Dodaj partnera


Szukaj partnera


Rejestracja


Dodaj użytkownika


Zarządzanie użytkownikami


Wyloguj się




Szukaj partnerów



Imię  
Nazwisko  
Firma  
VATIN  


Szukaj 



Imię

Nazwisko

Firma

VATIN

Adres


TestFirstName

TestLastName

TestCompanyName

1234567890

TestAddress


TestFirstName

TestLastName

TestCompanyName

123456789054907346

TestAddress




© 2016 - System zarządzania fakturami
        {""appName"":""Internet Explorer"",""requestId"":""f5b2d638161b48cc86da171dd64b9451""}    ";
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'fillTheSecondPartner'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class fillTheSecondPartnerParams
    {

        #region Fields
        /// <summary>
        /// Type 'testName' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditText = "testName";

        /// <summary>
        /// Type '{Tab}' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'testLastName' in 'lastName' text box
        /// </summary>
        public string UILastNameEditText = "testLastName";

        /// <summary>
        /// Type '{Tab}' in 'lastName' text box
        /// </summary>
        public string UILastNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'testCompanyName' in 'companyName' text box
        /// </summary>
        public string UICompanyNameEditText = "testCompanyName";

        /// <summary>
        /// Type '{Tab}' in 'companyName' text box
        /// </summary>
        public string UICompanyNameEditSendKeys = "{Tab}";

        /// <summary>
        /// Type '1' in 'VATIN' text box
        /// </summary>
        public string UIVATINEditText = "1";

        /// <summary>
        /// Type '{Tab}' in 'VATIN' text box
        /// </summary>
        public string UIVATINEditSendKeys = "{Tab}";

        /// <summary>
        /// Type 'address' in 'address' text box
        /// </summary>
        public string UIAddressEditText = "address";
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogowanieSystemzarząWindow : BrowserWindow
    {

        public UILogowanieSystemzarząWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Logowanie - System zarządzania fakturami";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            this.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami");
            this.WindowTitles.Add("AddPartner - System zarządzania fakturami");
            this.WindowTitles.Add("SearchInvoice - System zarządzania fakturami");
            #endregion
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties
        public UILogowanieSystemzarząDocument UILogowanieSystemzarząDocument
        {
            get
            {
                if ((this.mUILogowanieSystemzarząDocument == null))
                {
                    this.mUILogowanieSystemzarząDocument = new UILogowanieSystemzarząDocument(this);
                }
                return this.mUILogowanieSystemzarząDocument;
            }
        }

        public UIWyszukiwarkafakturSyDocument UIWyszukiwarkafakturSyDocument
        {
            get
            {
                if ((this.mUIWyszukiwarkafakturSyDocument == null))
                {
                    this.mUIWyszukiwarkafakturSyDocument = new UIWyszukiwarkafakturSyDocument(this);
                }
                return this.mUIWyszukiwarkafakturSyDocument;
            }
        }

        public UIAddPartnerSystemzarzDocument UIAddPartnerSystemzarzDocument
        {
            get
            {
                if ((this.mUIAddPartnerSystemzarzDocument == null))
                {
                    this.mUIAddPartnerSystemzarzDocument = new UIAddPartnerSystemzarzDocument(this);
                }
                return this.mUIAddPartnerSystemzarzDocument;
            }
        }

        public UISearchInvoiceSystemzDocument UISearchInvoiceSystemzDocument
        {
            get
            {
                if ((this.mUISearchInvoiceSystemzDocument == null))
                {
                    this.mUISearchInvoiceSystemzDocument = new UISearchInvoiceSystemzDocument(this);
                }
                return this.mUISearchInvoiceSystemzDocument;
            }
        }
        #endregion

        #region Fields
        private UILogowanieSystemzarząDocument mUILogowanieSystemzarząDocument;

        private UIWyszukiwarkafakturSyDocument mUIWyszukiwarkafakturSyDocument;

        private UIAddPartnerSystemzarzDocument mUIAddPartnerSystemzarzDocument;

        private UISearchInvoiceSystemzDocument mUISearchInvoiceSystemzDocument;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogowanieSystemzarząDocument : HtmlDocument
    {

        public UILogowanieSystemzarząDocument(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Logowanie - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/auth/login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/auth/login?ReturnUrl=%2F";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            #endregion
        }

        #region Properties
        public HtmlEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "login";
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" class=\"input-sm form-contro";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILoginEdit.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }

        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"input-sm form-con";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }

        public UILogInFormCustom UILogInFormCustom
        {
            get
            {
                if ((this.mUILogInFormCustom == null))
                {
                    this.mUILogInFormCustom = new UILogInFormCustom(this);
                }
                return this.mUILogInFormCustom;
            }
        }
        #endregion

        #region Fields
        private HtmlEdit mUILoginEdit;

        private HtmlEdit mUIPasswordEdit;

        private UILogInFormCustom mUILogInFormCustom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogInFormCustom : HtmlCustom
    {

        public UILogInFormCustom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "logInForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "form-inline";
            this.FilterProperties["ControlDefinition"] = "class=\"form-inline\" id=\"logInForm\" actio";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            #endregion
        }

        #region Properties
        public HtmlButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log In";
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn margin-top-10 margin-bottom-10";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn margin-top-10 margin-bottom-1";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUILogInButton.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        #endregion

        #region Fields
        private HtmlButton mUILogInButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWyszukiwarkafakturSyDocument : HtmlDocument
    {

        public UIWyszukiwarkafakturSyDocument(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Wyszukiwarka faktur - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/";
            this.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami");
            #endregion
        }

        #region Properties
        public HtmlHyperlink UIDodajpartneraHyperlink
        {
            get
            {
                if ((this.mUIDodajpartneraHyperlink == null))
                {
                    this.mUIDodajpartneraHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDodajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDodajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDodajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDodajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Dodaj partnera";
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/AddPartner";
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:56133/Home/AddPartner";
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/AddPartner\"";
                    this.mUIDodajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIDodajpartneraHyperlink.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIDodajpartneraHyperlink;
            }
        }

        public HtmlHyperlink UISzukajpartneraHyperlink
        {
            get
            {
                if ((this.mUISzukajpartneraHyperlink == null))
                {
                    this.mUISzukajpartneraHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISzukajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISzukajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISzukajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISzukajpartneraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Szukaj partnera";
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/SearchPartner";
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:56133/Home/SearchPartner";
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/SearchPartner\"";
                    this.mUISzukajpartneraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUISzukajpartneraHyperlink.WindowTitles.Add("Wyszukiwarka faktur - System zarządzania fakturami");
                    #endregion
                }
                return this.mUISzukajpartneraHyperlink;
            }
        }
        #endregion

        #region Fields
        private HtmlHyperlink mUIDodajpartneraHyperlink;

        private HtmlHyperlink mUISzukajpartneraHyperlink;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddPartnerSystemzarzDocument : HtmlDocument
    {

        public UIAddPartnerSystemzarzDocument(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AddPartner - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/AddPartner";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/Home/AddPartner";
            this.WindowTitles.Add("AddPartner - System zarządzania fakturami");
            #endregion
        }

        #region Properties
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "firstName";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "firstName";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"firstName\" class=\"input-sm form-co";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIFirstNameEdit.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }

        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "lastName";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "lastName";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"lastName\" class=\"input-sm form-con";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUILastNameEdit.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }

        public HtmlEdit UICompanyNameEdit
        {
            get
            {
                if ((this.mUICompanyNameEdit == null))
                {
                    this.mUICompanyNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICompanyNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "companyName";
                    this.mUICompanyNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "companyName";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"companyName\" class=\"input-sm form-";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUICompanyNameEdit.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUICompanyNameEdit;
            }
        }

        public HtmlEdit UIVATINEdit
        {
            get
            {
                if ((this.mUIVATINEdit == null))
                {
                    this.mUIVATINEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIVATINEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "vatin";
                    this.mUIVATINEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "vatin";
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "VATIN";
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"vatin\" class=\"input-sm form-contro";
                    this.mUIVATINEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIVATINEdit.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIVATINEdit;
            }
        }

        public HtmlEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "address";
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "address";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"address\" class=\"input-sm form-cont";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIAddressEdit.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }

        public HtmlButton UIDodajButton
        {
            get
            {
                if ((this.mUIDodajButton == null))
                {
                    this.mUIDodajButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIDodajButton.SearchProperties[HtmlButton.PropertyNames.Id] = "searchButton";
                    this.mUIDodajButton.SearchProperties[HtmlButton.PropertyNames.Name] = "searchButton";
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Dodaj";
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn margin-top-10 margin-bottom-10";
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"searchButton\" class=\"btn margin-to";
                    this.mUIDodajButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIDodajButton.WindowTitles.Add("AddPartner - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIDodajButton;
            }
        }
        #endregion

        #region Fields
        private HtmlEdit mUIFirstNameEdit;

        private HtmlEdit mUILastNameEdit;

        private HtmlEdit mUICompanyNameEdit;

        private HtmlEdit mUIVATINEdit;

        private HtmlEdit mUIAddressEdit;

        private HtmlButton mUIDodajButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISearchInvoiceSystemzDocument : HtmlDocument
    {

        public UISearchInvoiceSystemzDocument(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "SearchInvoice - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/SearchPartner";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/Home/SearchPartner";
            this.WindowTitles.Add("SearchInvoice - System zarządzania fakturami");
            #endregion
        }

        #region Properties
        public HtmlButton UISzukajButton
        {
            get
            {
                if ((this.mUISzukajButton == null))
                {
                    this.mUISzukajButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUISzukajButton.SearchProperties[HtmlButton.PropertyNames.Id] = "searchForPartnersButton";
                    this.mUISzukajButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISzukajButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Szukaj";
                    this.mUISzukajButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISzukajButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISzukajButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn margin-top-10 margin-bottom-10";
                    this.mUISzukajButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn margin-top-10 margin-bottom-1";
                    this.mUISzukajButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISzukajButton.WindowTitles.Add("SearchInvoice - System zarządzania fakturami");
                    #endregion
                }
                return this.mUISzukajButton;
            }
        }
        public HtmlEdit UICompanyNameEdit
        {
            get
            {
                if ((this.mUICompanyNameEdit == null))
                {
                    this.mUICompanyNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICompanyNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "companyName";
                    this.mUICompanyNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "companyName";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"companyName\" class=\"input-sm form-";
                    this.mUICompanyNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUICompanyNameEdit.WindowTitles.Add("SearchInvoice - System zarządzania fakturami");
                    #endregion
                }
                return this.mUICompanyNameEdit;
            }
        }
        #endregion

        #region Fields
        private HtmlButton mUISzukajButton;

        private HtmlEdit mUICompanyNameEdit;
        #endregion
    }
}
