// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UserFunctionalTests.UIMapRegistrationClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMapRegistration
    {
        
        /// <summary>
        /// clickRegisterAction
        /// </summary>
        public void clickRegisterAction()
        {
            #region Variable Declarations
            HtmlHyperlink uIRejestracjaHyperlink = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UIRejestracjaHyperlink;
            #endregion

            // Click 'Rejestracja' link
            Mouse.Click(uIRejestracjaHyperlink, new Point(36, 22));
        }
        
        /// <summary>
        /// fillRegisterFormAction - Use 'fillRegisterFormActionParams' to pass parameters into this method.
        /// </summary>
        public void fillRegisterFormAction(string uniqueId)
        {
            #region Variable Declarations
            HtmlEdit uILoginEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UILoginEdit;
            HtmlEdit uIEmailEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIEmailEdit;
            HtmlEdit uIPasswordEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIPasswordEdit;
            HtmlEdit uIPasswordConfirmationEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIPasswordConfirmationEdit;
            HtmlEdit uIFirstNameEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UILastNameEdit;
            #endregion

            // Type 'testLogin' in 'login' text box
            uILoginEdit.Text = "testLogin_" + uniqueId;

            // Type '{Tab}' in 'login' text box
            Keyboard.SendKeys(uILoginEdit, this.fillRegisterFormActionParams.UILoginEditSendKeys, ModifierKeys.None);

            // Type 'testEmail@email.com' in 'email' text box
            uIEmailEdit.Text = "test" + uniqueId + "@email.com";

            // Type '{Tab}' in 'email' text box
            Keyboard.SendKeys(uIEmailEdit, this.fillRegisterFormActionParams.UIEmailEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.fillRegisterFormActionParams.UIPasswordEditPassword;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.fillRegisterFormActionParams.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'PasswordConfirmation' text box
            uIPasswordConfirmationEdit.Password = this.fillRegisterFormActionParams.UIPasswordConfirmationEditPassword;

            // Type '{Tab}' in 'PasswordConfirmation' text box
            Keyboard.SendKeys(uIPasswordConfirmationEdit, this.fillRegisterFormActionParams.UIPasswordConfirmationEditSendKeys, ModifierKeys.None);

            // Type 'testName' in 'firstName' text box
            uIFirstNameEdit.Text = this.fillRegisterFormActionParams.UIFirstNameEditText;

            // Type '{Tab}' in 'firstName' text box
            Keyboard.SendKeys(uIFirstNameEdit, this.fillRegisterFormActionParams.UIFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'testLastName' in 'lastName' text box
            uILastNameEdit.Text = this.fillRegisterFormActionParams.UILastNameEditText;
        }
        
        /// <summary>
        /// registerAssertions
        /// </summary>
        public void registerAssertions()
        {
            #region Variable Declarations
            HtmlEdit uILoginEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UILoginEdit;
            HtmlEdit uIEmailEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIEmailEdit;
            HtmlEdit uIFirstNameEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UILastNameEdit;
            #endregion

            // Verify that the 'Text' property of 'login' text box is not equal to 'null'
            Assert.IsNotNull(uILoginEdit.Text);

            // Verify that the 'Text' property of 'email' text box is not equal to 'null'
            Assert.IsNotNull(uIEmailEdit.Text);

            // Verify that the 'Text' property of 'firstName' text box is not equal to 'null'
            Assert.IsNotNull(uIFirstNameEdit.Text);

            // Verify that the 'Text' property of 'lastName' text box is not equal to 'null'
            Assert.IsNotNull(uILastNameEdit.Text);
        }
        
        /// <summary>
        /// registerSubmitAction
        /// </summary>
        public void registerSubmitAction()
        {
            #region Variable Declarations
            HtmlButton uIZarejestrujsięButton = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument.UIRegisterFormCustom.UIZarejestrujsięButton;
            #endregion

            // Click 'Zarejestruj się' button
            Mouse.Click(uIZarejestrujsięButton, new Point(62, 20));
        }
        
        /// <summary>
        /// loginWithCreatedUserAction - Use 'loginWithCreatedUserActionParams' to pass parameters into this method.
        /// </summary>
        public void loginWithCreatedUserAction(string unique)
        {
            #region Variable Declarations
            HtmlEdit uILoginEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILoginEdit;
            HtmlEdit uIPasswordEdit = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UIPasswordEdit;
            HtmlButton uILogInButton = this.UILogowanieSystemzarząWindow.UILogowanieSystemzarząDocument.UILogInFormCustom.UILogInButton;
            #endregion

            // Type 'testLogin' in 'login' text box
            uILoginEdit.Text = "testLogin_" + unique;

            // Type '{Tab}' in 'login' text box
            Keyboard.SendKeys(uILoginEdit, this.loginWithCreatedUserActionParams.UILoginEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.loginWithCreatedUserActionParams.UIPasswordEditPassword;

            // Click 'Log In' button
            Mouse.Click(uILogInButton, new Point(31, 13));
        }
        
        /// <summary>
        /// incorrectUserAssertion - Use 'incorrectUserAssertionExpectedValues' to pass parameters into this method.
        /// </summary>
        public void incorrectUserAssertion()
        {
            #region Variable Declarations
            HtmlDocument uIRejestracjaSystemzarDocument = this.UIRejestracjaSystemzarWindow.UIRejestracjaSystemzarDocument;
            #endregion
           
            StringAssert.Contains(uIRejestracjaSystemzarDocument.InnerText, "Błędny login");
        }
        
        #region Properties
        public virtual fillRegisterFormActionParams fillRegisterFormActionParams
        {
            get
            {
                if ((this.mfillRegisterFormActionParams == null))
                {
                    this.mfillRegisterFormActionParams = new fillRegisterFormActionParams();
                }
                return this.mfillRegisterFormActionParams;
            }
        }
        
        public virtual loginWithCreatedUserActionParams loginWithCreatedUserActionParams
        {
            get
            {
                if ((this.mloginWithCreatedUserActionParams == null))
                {
                    this.mloginWithCreatedUserActionParams = new loginWithCreatedUserActionParams();
                }
                return this.mloginWithCreatedUserActionParams;
            }
        }
        
        public virtual incorrectUserAssertionExpectedValues incorrectUserAssertionExpectedValues
        {
            get
            {
                if ((this.mincorrectUserAssertionExpectedValues == null))
                {
                    this.mincorrectUserAssertionExpectedValues = new incorrectUserAssertionExpectedValues();
                }
                return this.mincorrectUserAssertionExpectedValues;
            }
        }
        
        public UILogowanieSystemzarząWindow UILogowanieSystemzarząWindow
        {
            get
            {
                if ((this.mUILogowanieSystemzarząWindow == null))
                {
                    this.mUILogowanieSystemzarząWindow = new UILogowanieSystemzarząWindow();
                }
                return this.mUILogowanieSystemzarząWindow;
            }
        }
        
        public UIRejestracjaSystemzarWindow UIRejestracjaSystemzarWindow
        {
            get
            {
                if ((this.mUIRejestracjaSystemzarWindow == null))
                {
                    this.mUIRejestracjaSystemzarWindow = new UIRejestracjaSystemzarWindow();
                }
                return this.mUIRejestracjaSystemzarWindow;
            }
        }
        #endregion
        
        #region Fields
        private fillRegisterFormActionParams mfillRegisterFormActionParams;
        
        private loginWithCreatedUserActionParams mloginWithCreatedUserActionParams;
        
        private incorrectUserAssertionExpectedValues mincorrectUserAssertionExpectedValues;
        
        private UILogowanieSystemzarząWindow mUILogowanieSystemzarząWindow;
        
        private UIRejestracjaSystemzarWindow mUIRejestracjaSystemzarWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'fillRegisterFormAction'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class fillRegisterFormActionParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'testLogin' in 'login' text box
        /// </summary>
        public string UILoginEditText = "testLogin";
        
        /// <summary>
        /// Type '{Tab}' in 'login' text box
        /// </summary>
        public string UILoginEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'testEmail@email.com' in 'email' text box
        /// </summary>
        public string UIEmailEditText = "testEmail@email.com";
        
        /// <summary>
        /// Type '{Tab}' in 'email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "QWwOodIXpSM441BCNCWNvH9k+8fhegdI";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'PasswordConfirmation' text box
        /// </summary>
        public string UIPasswordConfirmationEditPassword = "QWwOodIXpSM441BCNCWNvH9k+8fhegdI";
        
        /// <summary>
        /// Type '{Tab}' in 'PasswordConfirmation' text box
        /// </summary>
        public string UIPasswordConfirmationEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'testName' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditText = "testName";
        
        /// <summary>
        /// Type '{Tab}' in 'firstName' text box
        /// </summary>
        public string UIFirstNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'testLastName' in 'lastName' text box
        /// </summary>
        public string UILastNameEditText = "testLastName";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'loginWithCreatedUserAction'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class loginWithCreatedUserActionParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'testLogin' in 'login' text box
        /// </summary>
        public string UILoginEditText = "testLogin";
        
        /// <summary>
        /// Type '{Tab}' in 'login' text box
        /// </summary>
        public string UILoginEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "QWwOodIXpSM441BCNCWNvH9k+8fhegdI";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'incorrectUserAssertion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class incorrectUserAssertionExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Rejestracja - System zarządzania fakturami' document contains 'Błędny login.
        ///
        ///
        ///
        ///
        /// Faktury 
        ///
        ///Rejestracja
        ///
        ///
        ///
        ///Zarejestruj się
        ///
        ///Błędny login.
        ///
        ///
        ///Login:  
        ///Email:  
        ///Hasło:  
        ///Powtórz hasło:  
        ///Imię:  
        ///Nazwisko:  
        ///
        ///
        ///Zarejestruj się 
        ///
        ///
        ///© 2016 - System zarządzania fakturami
        ///    {"appName":"Internet Explorer","requestId":"ba617908a9d74e3bbca0c9f579113f0b"}    '
        /// </summary>
        public string UIRejestracjaSystemzarDocumentInnerText = @"Błędny login.




 Faktury 

Rejestracja



Zarejestruj się

Błędny login.


Login:  
Email:  
Hasło:  
Powtórz hasło:  
Imię:  
Nazwisko:  


Zarejestruj się 


© 2016 - System zarządzania fakturami
    {""appName"":""Internet Explorer"",""requestId"":""ba617908a9d74e3bbca0c9f579113f0b""}    ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogowanieSystemzarząWindow : BrowserWindow
    {
        
        public UILogowanieSystemzarząWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Logowanie - System zarządzania fakturami";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UILogowanieSystemzarząDocument UILogowanieSystemzarząDocument
        {
            get
            {
                if ((this.mUILogowanieSystemzarząDocument == null))
                {
                    this.mUILogowanieSystemzarząDocument = new UILogowanieSystemzarząDocument(this);
                }
                return this.mUILogowanieSystemzarząDocument;
            }
        }
        #endregion
        
        #region Fields
        private UILogowanieSystemzarząDocument mUILogowanieSystemzarząDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogowanieSystemzarząDocument : HtmlDocument
    {
        
        public UILogowanieSystemzarząDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Logowanie - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/auth/login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/auth/login?ReturnUrl=%2F";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRejestracjaHyperlink
        {
            get
            {
                if ((this.mUIRejestracjaHyperlink == null))
                {
                    this.mUIRejestracjaHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRejestracjaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRejestracjaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRejestracjaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRejestracjaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Rejestracja";
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Auth/Register";
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:56133/Auth/Register";
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Auth/Register\"";
                    this.mUIRejestracjaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIRejestracjaHyperlink.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIRejestracjaHyperlink;
            }
        }
        
        public HtmlEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "login";
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" class=\"input-sm form-contro";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILoginEdit.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"input-sm form-con";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UILogInFormCustom UILogInFormCustom
        {
            get
            {
                if ((this.mUILogInFormCustom == null))
                {
                    this.mUILogInFormCustom = new UILogInFormCustom(this);
                }
                return this.mUILogInFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRejestracjaHyperlink;
        
        private HtmlEdit mUILoginEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private UILogInFormCustom mUILogInFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogInFormCustom : HtmlCustom
    {
        
        public UILogInFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "logInForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "form-inline";
            this.FilterProperties["ControlDefinition"] = "class=\"form-inline\" id=\"logInForm\" actio";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Logowanie - System zarządzania fakturami");
            #endregion
        }
        
        #region Properties
        public HtmlButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log In";
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn margin-top-10 margin-bottom-10";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn margin-top-10 margin-bottom-1";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUILogInButton.WindowTitles.Add("Logowanie - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUILogInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRejestracjaSystemzarWindow : BrowserWindow
    {
        
        public UIRejestracjaSystemzarWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Rejestracja - System zarządzania fakturami";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIRejestracjaSystemzarDocument UIRejestracjaSystemzarDocument
        {
            get
            {
                if ((this.mUIRejestracjaSystemzarDocument == null))
                {
                    this.mUIRejestracjaSystemzarDocument = new UIRejestracjaSystemzarDocument(this);
                }
                return this.mUIRejestracjaSystemzarDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIRejestracjaSystemzarDocument mUIRejestracjaSystemzarDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRejestracjaSystemzarDocument : HtmlDocument
    {
        
        public UIRejestracjaSystemzarDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Rejestracja - System zarządzania fakturami";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Auth/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56133/Auth/Register";
            this.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "login";
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" class=\"input-sm form-contro";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILoginEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"email\" class=\"input-sm form-contro";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIEmailEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"input-sm form-con";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UIPasswordConfirmationEdit
        {
            get
            {
                if ((this.mUIPasswordConfirmationEdit == null))
                {
                    this.mUIPasswordConfirmationEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordConfirmationEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "PasswordConfirmation";
                    this.mUIPasswordConfirmationEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "PasswordConfirmation";
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"PasswordConfirmation\" class=\"input";
                    this.mUIPasswordConfirmationEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIPasswordConfirmationEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIPasswordConfirmationEdit;
            }
        }
        
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "firstName";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "firstName";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"firstName\" class=\"input-sm form-co";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIFirstNameEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "lastName";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "lastName";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-sm form-control margin-right-10 margin-left-20";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"lastName\" class=\"input-sm form-con";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUILastNameEdit.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }
        
        public UIRegisterFormCustom UIRegisterFormCustom
        {
            get
            {
                if ((this.mUIRegisterFormCustom == null))
                {
                    this.mUIRegisterFormCustom = new UIRegisterFormCustom(this);
                }
                return this.mUIRegisterFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUILoginEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUIPasswordConfirmationEdit;
        
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlEdit mUILastNameEdit;
        
        private UIRegisterFormCustom mUIRegisterFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRegisterFormCustom : HtmlCustom
    {
        
        public UIRegisterFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "registerForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "form-inline";
            this.FilterProperties["ControlDefinition"] = "class=\"form-inline\" id=\"registerForm\" ac";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIZarejestrujsięButton
        {
            get
            {
                if ((this.mUIZarejestrujsięButton == null))
                {
                    this.mUIZarejestrujsięButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIZarejestrujsięButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIZarejestrujsięButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIZarejestrujsięButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Zarejestruj się";
                    this.mUIZarejestrujsięButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIZarejestrujsięButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIZarejestrujsięButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn margin-top-10 margin-bottom-10";
                    this.mUIZarejestrujsięButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn margin-top-10 margin-bottom-1";
                    this.mUIZarejestrujsięButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIZarejestrujsięButton.WindowTitles.Add("Rejestracja - System zarządzania fakturami");
                    #endregion
                }
                return this.mUIZarejestrujsięButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIZarejestrujsięButton;
        #endregion
    }
}
